#!/usr/bin/env python3
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Required Notice: Copyright 2026 Solipsist Studios Inc. (https://solipsist.studio)

"""sogst_ply.py - the 4D interchange PLY: reader, writer, CLI.

This is the seam between the two halves of the .sogst toolchain.  Python
produces per-splat spacetime data.  A separate encoder (splat-transform, in
TypeScript) packs it into the .sogst container.  Their entire contract is
one binary PLY, specified in docs/sogst-format.md section 7.  Read that
before changing anything here.

    19 REQUIRED float32 columns, in this order:
        x y z                       position AT t_center (not at t=0)
        rot_0..rot_3                quaternion, W FIRST
        scale_0..scale_2            natural-log space
        opacity                     logit space (peak, at t_center)
        f_dc_0..f_dc_2              raw SH DC coefficients, not RGB
        vx vy vz                    scene units per second
        t_center                    seconds, absolute clip time
        t_sigma                     STANDARD DEVIATION in seconds, > 0

    OPTIONAL:
        f_rest_0..f_rest_44         channel-major: index j*15 + k
        ax ay az                    RAW dt^2 coefficient, not a/2

Clip-level scalars are not per-vertex, so they ride in PLY comments:

    comment sogst.time_min 0.0      REQUIRED
    comment sogst.time_max 10.0     REQUIRED
    comment sogst.fps 30.0          REQUIRED
    comment sogst.motion_degree 1   optional, advisory
    comment sogst.cov2d_scale 1.0 1.0   optional

read_sogst_ply() raises when a required scalar is in neither the comments
nor the sidecar, rather than defaulting.  That is deliberate and it is the
single most important line of defence in this file: a defaulted fps
produces an asset that renders perfectly and plays at the wrong speed,
which no test catches and no reviewer sees.  An optional <name>.sogst.json
sidecar overrides the comments, for toolchains that cannot write comments
or that strip them (spec section 7.3: either carrier alone is conforming).

CLI (convert an already-packed .sogst archive back into interchange PLY):

    python sogst_ply.py --input scene.sogst --output scene.ply [--sidecar]

Numpy only (no torch, no PIL), so this module stays trivially portable.
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sogst_io import SOGST_FIELDS  # noqa: E402

# Column blocks, in the order they appear in the file.
PLY_BASE_COLUMNS = list(SOGST_FIELDS)                       # the 19 required
PLY_SH_COLUMNS = [f'f_rest_{i}' for i in range(45)]           # all 45 or none
PLY_ACCEL_COLUMNS = ['ax', 'ay', 'az']                        # all 3 or none

# Comment keys carrying clip-level scalars.
PLY_COMMENT_PREFIX = 'sogst.'
PLY_REQUIRED_COMMENTS = ('time_min', 'time_max', 'fps')
SIDECAR_SUFFIX = '.sogst.json'

# Revision of the PLY contract itself (not the container version).
SOGST_PLY_VERSION = 1


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------

def _fmt(value: float) -> str:
    """Format a float for a PLY comment without losing precision."""
    return repr(float(value))


def write_sogst_ply(out_path, fields, time_min, time_max, fps,
                    cov2d_scale=None, generator='volumetric-capture-pipeline'):
    """Write per-splat spacetime data as an interchange PLY.

    Parameters
    ----------
    out_path    : Destination .ply path.
    fields      : Maps column name -> float array.  Must contain every name
                  in PLY_BASE_COLUMNS as a length-N 1-D array.  May contain
                  'f_rest' as [N, 45] (or the 45 individual f_rest_* names),
                  and 'ax'/'ay'/'az'.
    time_min,
    time_max    : Clip bounds in seconds.
    fps         : Advisory frame rate.  Recorded, never used to evaluate the
                  model, and REQUIRED: see the module docstring.
    cov2d_scale : Optional (kx, ky) screen-space covariance multiplier.
    generator   : Free-form producer string for a plain PLY comment.

    Returns the number of splats written.
    """
    columns, n = _collect_columns(fields)

    comments = [
        f'generated by {generator}',
        f'{PLY_COMMENT_PREFIX}version {SOGST_PLY_VERSION}',
        f'{PLY_COMMENT_PREFIX}time_min {_fmt(time_min)}',
        f'{PLY_COMMENT_PREFIX}time_max {_fmt(time_max)}',
        f'{PLY_COMMENT_PREFIX}fps {_fmt(fps)}',
        f'{PLY_COMMENT_PREFIX}motion_degree {2 if "ax" in columns else 1}',
    ]
    if cov2d_scale is not None:
        comments.append(f'{PLY_COMMENT_PREFIX}cov2d_scale '
                        f'{_fmt(cov2d_scale[0])} {_fmt(cov2d_scale[1])}')

    names = list(columns)
    header = ['ply', 'format binary_little_endian 1.0']
    header += [f'comment {c}' for c in comments]
    header.append(f'element vertex {n}')
    header += [f'property float {name}' for name in names]
    header.append('end_header')

    # Interleave to AoS in one shot: [N, C] float32, written verbatim.
    table = np.empty((n, len(names)), dtype=np.float32)
    for i, name in enumerate(names):
        table[:, i] = columns[name]

    with open(out_path, 'wb') as fp:
        fp.write(('\n'.join(header) + '\n').encode('ascii'))
        fp.write(np.ascontiguousarray(table).tobytes())
    return n


def write_sogst_sidecar(ply_path, time_min, time_max, fps, cov2d_scale=None,
                        motion_degree=1):
    """Write the optional <name>.sogst.json sidecar next to a PLY.

    For toolchains that cannot write PLY comments or that strip them.  The
    spec (section 7.3) requires the clip scalars in at least one carrier,
    comments or sidecar, and prefers the comments.  This writer always
    emits the comments, so its sidecar is redundancy.  When both are
    present the sidecar wins.  Returns the sidecar path.
    """
    base = ply_path[:-4] if ply_path.endswith('.ply') else ply_path
    path = base + SIDECAR_SUFFIX
    payload = {
        'version': SOGST_PLY_VERSION,
        'time_min': float(time_min),
        'time_max': float(time_max),
        'fps': float(fps),
        'motion_degree': int(motion_degree),
    }
    if cov2d_scale is not None:
        payload['cov2d_scale'] = [float(cov2d_scale[0]), float(cov2d_scale[1])]
    with open(path, 'w') as fp:
        json.dump(payload, fp, indent=2)
        fp.write('\n')
    return path


def _collect_columns(fields):
    """Validate `fields` and flatten it to an ordered name -> float array map.

    Every check here exists because the corresponding mistake is silent:
    nothing downstream cross-checks column lengths, an f_rest block that is
    partially present packs garbage into the SH textures, and t_sigma <= 0
    divides by zero inside the temporal exponent.
    """
    missing = [c for c in PLY_BASE_COLUMNS if c not in fields]
    if missing:
        raise ValueError(f'write_sogst_ply: missing required columns: {missing}')

    columns = {}
    for name in PLY_BASE_COLUMNS:
        columns[name] = np.asarray(fields[name], dtype=np.float32).ravel()
    n = len(columns['x'])

    # Higher-order SH: accept either the [N, 45] block or 45 named columns.
    f_rest = fields.get('f_rest')
    if f_rest is not None:
        f_rest = np.asarray(f_rest, dtype=np.float32)
        if f_rest.ndim != 2 or f_rest.shape[1] != 45:
            raise ValueError('write_sogst_ply: f_rest must be [N, 45] '
                             f'(channel-major, index j*15+k), got {f_rest.shape}')
        for i, name in enumerate(PLY_SH_COLUMNS):
            columns[name] = f_rest[:, i]
    else:
        present = [c for c in PLY_SH_COLUMNS if c in fields]
        if present and len(present) != 45:
            raise ValueError('write_sogst_ply: higher-order SH is all-or-nothing; '
                             f'got {len(present)} of 45 f_rest_* columns')
        for name in present:
            columns[name] = np.asarray(fields[name], dtype=np.float32).ravel()

    # Degree-2 motion: all three axes or none.
    present = [c for c in PLY_ACCEL_COLUMNS if c in fields]
    if present and len(present) != 3:
        raise ValueError('write_sogst_ply: accel is all-or-nothing; '
                         f'got {present}, need all of {PLY_ACCEL_COLUMNS}')
    for name in present:
        columns[name] = np.asarray(fields[name], dtype=np.float32).ravel()

    bad = {name: len(a) for name, a in columns.items() if len(a) != n}
    if bad:
        raise ValueError(f'write_sogst_ply: column length mismatch against '
                         f'N={n} (from x): {bad}')

    t_sigma = columns['t_sigma']
    if not np.all(np.isfinite(t_sigma)) or np.any(t_sigma <= 0):
        n_bad = int((~np.isfinite(t_sigma) | (t_sigma <= 0)).sum())
        raise ValueError(f'write_sogst_ply: t_sigma must be finite and > 0 '
                         f'(it is a standard deviation, not a variance); '
                         f'{n_bad:,} of {n:,} splats violate this')
    return columns, n


# ---------------------------------------------------------------------------
# Reader
# ---------------------------------------------------------------------------

def ply_vertex_count(ply_path):
    """Splat count from a PLY header, without reading the body.

    The bake stages use this to size the SH codebook against a multi-hundred-
    megabyte PLY.  Reading the whole file to learn one integer would dominate
    their runtime.
    """
    with open(ply_path, 'rb') as fp:
        while True:
            line = fp.readline()
            if not line:
                raise ValueError(f'{ply_path}: truncated PLY header')
            text = line.decode('ascii', 'replace').strip()
            if text.startswith('element vertex'):
                return int(text.split()[-1])
            if text == 'end_header':
                raise ValueError(f'{ply_path}: no "element vertex" in header')


def read_sogst_ply(ply_path, require_scalars=True):
    """Read an interchange PLY into (header, fields).

    `fields` matches what the packer consumes (1-D arrays
    under the SOGST_FIELDS names, plus 'f_rest' as [N, 45] and 'ax'/'ay'/
    'az' when present), so it feeds pack_sogst() directly.

    `header` carries time_min, time_max, fps, count, motion_degree and an
    optional cov2d_scale.  With require_scalars=True (the default) a
    missing time_min/time_max/fps is an error rather than a default.  See
    the module docstring for why that matters more than it looks.
    """
    with open(ply_path, 'rb') as fp:
        header_bytes = b''
        while not header_bytes.endswith(b'end_header\n'):
            line = fp.readline()
            if not line:
                raise ValueError(f'{ply_path}: truncated PLY header')
            header_bytes += line

        text = header_bytes.decode('ascii')
        if 'binary_little_endian' not in text:
            raise ValueError(f'{ply_path}: expected binary_little_endian PLY')

        n = None
        names = []
        comments = {}
        for line in text.splitlines():
            if line.startswith('element vertex'):
                n = int(line.split()[-1])
            elif line.startswith('property float '):
                names.append(line.split()[-1])
            elif line.startswith('property'):
                raise ValueError(f'{ply_path}: non-float property: {line!r} -- '
                                 'the interchange PLY is all float32')
            elif line.startswith('comment '):
                body = line[len('comment '):].strip()
                if body.startswith(PLY_COMMENT_PREFIX):
                    key, _, value = body[len(PLY_COMMENT_PREFIX):].partition(' ')
                    comments[key] = value.strip()
        if n is None:
            raise ValueError(f'{ply_path}: no "element vertex" in header')

        data = np.fromfile(fp, dtype=np.float32, count=n * len(names))
    if data.size != n * len(names):
        raise ValueError(f'{ply_path}: truncated body -- expected {n * len(names):,} '
                         f'float32, got {data.size:,}')
    data = data.reshape(n, len(names))
    raw = {name: data[:, i] for i, name in enumerate(names)}

    missing = [c for c in PLY_BASE_COLUMNS if c not in raw]
    if missing:
        raise ValueError(f'{ply_path}: missing required columns: {missing}')

    fields = {name: raw[name] for name in PLY_BASE_COLUMNS}
    sh_present = [c for c in PLY_SH_COLUMNS if c in raw]
    if sh_present:
        if len(sh_present) != 45:
            raise ValueError(f'{ply_path}: {len(sh_present)} of 45 f_rest_* columns '
                             '-- higher-order SH is all-or-nothing')
        fields['f_rest'] = np.stack([raw[c] for c in PLY_SH_COLUMNS], axis=1)
    accel_present = [c for c in PLY_ACCEL_COLUMNS if c in raw]
    if accel_present:
        if len(accel_present) != 3:
            raise ValueError(f'{ply_path}: accel is all-or-nothing, got {accel_present}')
        for c in PLY_ACCEL_COLUMNS:
            fields[c] = raw[c]

    # Sidecar overrides comments (spec section 7.3).  Either carrier alone
    # is conforming.  The sidecar exists for toolchains that cannot write
    # comments or that strip them.
    base = ply_path[:-4] if ply_path.endswith('.ply') else ply_path
    sidecar_path = base + SIDECAR_SUFFIX
    sidecar = {}
    if os.path.exists(sidecar_path):
        with open(sidecar_path) as fp:
            sidecar = json.load(fp)

    def scalar(key):
        if key in sidecar:
            return float(sidecar[key])
        if key in comments:
            return float(comments[key])
        return None

    header = {'count': n}
    absent = []
    for key in PLY_REQUIRED_COMMENTS:
        value = scalar(key)
        if value is None:
            absent.append(key)
        header[key] = value
    if absent and require_scalars:
        raise ValueError(
            f'{ply_path}: missing required clip scalar(s) {absent}. They belong in '
            f'"comment {PLY_COMMENT_PREFIX}<key> <value>" header lines or a '
            f'{SIDECAR_SUFFIX} sidecar. Refusing to substitute a default: a wrong '
            'fps or time range renders perfectly and plays at the wrong speed.')

    declared = sidecar.get('motion_degree', comments.get('motion_degree'))
    actual = 2 if accel_present else 1
    if declared is not None and int(declared) != actual:
        raise ValueError(f'{ply_path}: motion_degree says {int(declared)} but the file '
                         f'{"has" if accel_present else "has no"} accel columns')
    header['motion_degree'] = actual

    cov = sidecar.get('cov2d_scale')
    if cov is None and 'cov2d_scale' in comments:
        cov = comments['cov2d_scale'].split()
    if cov is not None:
        header['cov2d_scale'] = (float(cov[0]), float(cov[1]))

    return header, fields


# ---------------------------------------------------------------------------
# CLI: baked asset -> interchange PLY
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Unpack a .sogst archive into the 4D interchange PLY.',
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--input', required=True, help='Source .sogst archive')
    parser.add_argument('--output', required=True, help='Destination .ply path')
    parser.add_argument('--sidecar', action='store_true',
                        help='Also write the optional <name>.sogst.json sidecar')
    parser.add_argument('--verify', action='store_true',
                        help='Read the PLY back and assert it round-trips exactly')
    args = parser.parse_args()

    import zipfile
    if not zipfile.is_zipfile(args.input):
        sys.exit(f'{args.input}: not a .sogst archive (a .sogst file is a ZIP). '
                 'To produce an interchange PLY from a trainer artifact, use '
                 'bake_sogst.py --emit_ply.')
    from eval_render import decode_sogst_fields
    header, fields = decode_sogst_fields(args.input)
    # The archive has already been quantized once, and the PLY carries the
    # decoded values, so a repack quantizes twice.  Fine for fixtures and
    # cross-implementation checks, not for producing a shipping asset.
    # Bake those from the trainer via bake_sogst.py --emit_ply.
    print(f'Read {args.input}: {header["count"]:,} splats '
          '(already quantized once -- repacking will quantize twice)')
    cov = None

    n = write_sogst_ply(args.output, fields, header['time_min'], header['time_max'],
                        header['fps'], cov2d_scale=cov,
                        generator=f'volumetric-capture-pipeline sogst_ply from {os.path.basename(args.input)}')
    if args.sidecar:
        path = write_sogst_sidecar(args.output, header['time_min'], header['time_max'],
                                   header['fps'], cov2d_scale=cov,
                                   motion_degree=2 if 'ax' in fields else 1)
        print(f'  sidecar: {path}')

    size_mb = os.path.getsize(args.output) / 1024 / 1024
    cols = len(PLY_BASE_COLUMNS) + (45 if 'f_rest' in fields else 0) + (3 if 'ax' in fields else 0)
    print(f'Wrote {args.output}  ({n:,} splats x {cols} columns, {size_mb:.1f} MB)')

    if args.verify:
        back_header, back_fields = read_sogst_ply(args.output)
        assert back_header['count'] == n, 'count mismatch on read-back'
        for name in PLY_BASE_COLUMNS:
            ref = np.asarray(fields[name], dtype=np.float32).ravel()
            if not np.array_equal(back_fields[name], ref):
                raise AssertionError(f'round-trip mismatch in column {name}')
        if 'f_rest' in fields:
            ref = np.asarray(fields['f_rest'], dtype=np.float32)
            if not np.array_equal(back_fields['f_rest'], ref):
                raise AssertionError('round-trip mismatch in f_rest')
        print(f'  Verified: {cols} columns round-trip bit-exact, '
              f'scalars {back_header["time_min"]}..{back_header["time_max"]}s '
              f'@ {back_header["fps"]} fps')


if __name__ == '__main__':
    main()
